language: go
env:
  GO111MODULE=on

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0

script:
  - make lint test

deploy:
  provider: heroku
  api_key:
    secure: "CrQY4DMq25g5Kf+o83NQ+8GGs2vOjlYkZ9b94QByA4xQPhPHv52a+rqTxrFJAszYbNLJswkvOLcpauk92ByuAHvwdWCevy6y60hpbOBOQI3xXyMPDSta9UKU8r7E4lYPnEs77UKRUTAnLjwW9LlFSwKVkcGUr+u+OAqvrZARrin7cuPNzR3IbMEki5SOFEh8DsRnqZNnBwZwKSB2f1hHrXjirwrrYj77D4H/NrmvZUXFeKmzNq1iyDg1hhpTgNtss3DXYQNCgsOsWWDPkT+uwMKLD5qIhx11c5ciF3SP8cirOwPcC7V2Uv82yLQBHRlR990hMrXhZqZiMsScssNkEvDP8+tLXHjaZAlySgFjVruWWWTfMnfpPheQikvXsJJe4NlcVTQpnQAqV7vZ40Q628RHjibPoFrUTfE+EvOlSdGUY8TA6CsP7zoCfwCNp7Z6p53s+hK71ZAJKouUR6hs7BXkevKOpKukNcTpA0z85W4q9N1G9G8sJgmvormOCGXMbJoQM22uoIt6FViXtqlUfkNltopJo6BFYqJT/Qa0gG+ZdEqTp4CAlVp3sTLn8QL1zhAihRAbp3M4v6z3m/fs0hflpzNpkvD/Dun5vZNGcmS3jdO/Gh2nOeDaK3vnvQ9e/mmyC/Lwuda0ZRcVKVZhNoBqO/dY1/RQt97RnDv3TC0="
  app:
    master: fierce-lake-96105